version: '3.8'

services:
  google-drive-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-drive-service
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - google-drive-service-data:/app
    networks:
      - fogis-network
    environment:
      - FLASK_ENV=production
      - LOG_LEVEL=INFO

      - TZ=Europe/Stockholm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  google-drive-service-data:
    name: google-drive-service-data
    driver: local

networks:
  fogis-network:
    external: true