name: CI Status Tracker

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  get_pr_info:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.pull_requests[0] != null
    outputs:
      pr_number: ${{ steps.pr-info.outputs.PR_NUMBER }}
      ci_status: ${{ github.event.workflow_run.conclusion }}
    steps:
      - name: Get PR information
        id: pr-info
        run: |
          PR_NUMBER="${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "Processing PR #$PR_NUMBER with CI status: ${{ github.event.workflow_run.conclusion }}"

  track_ci_status:
    needs: get_pr_info
    uses: PitchConnect/.github/.github/workflows/ci-failure-tracker.yml@main
    with:
      project_id: 'PVT_kwDODF_kVc4A4M8N'
      project_number: 3
      ci_status: ${{ needs.get_pr_info.outputs.ci_status }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
