name: CI Status Tracker

on:
  workflow_run:
    workflows: ["*"]
    types: [completed]

jobs:
  get_pr_info:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.pull_requests != null && github.event.workflow_run.pull_requests != '[]'
    outputs:
      pr_number: ${{ steps.pr-info.outputs.PR_NUMBER }}
      ci_status: ${{ github.event.workflow_run.conclusion }}
    steps:
      - name: Get PR information
        id: pr-info
        run: |
          PR_ARRAY='${{ toJson(github.event.workflow_run.pull_requests) }}'
          if [ "$PR_ARRAY" != "[]" ] && [ "$PR_ARRAY" != "null" ]; then
            PR_NUMBER=$(echo "$PR_ARRAY" | jq -r '.[0].number // empty')
            if [ -n "$PR_NUMBER" ]; then
              echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
              echo "Processing PR #$PR_NUMBER with CI status: ${{ github.event.workflow_run.conclusion }}"
            else
              echo "No valid PR number found"
              exit 1
            fi
          else
            echo "No pull requests associated with this workflow run"
            exit 1
          fi

  track_ci_status:
    needs: get_pr_info
    uses: PitchConnect/.github/.github/workflows/ci-failure-tracker.yml@main
    with:
      project_id: 'PVT_kwDODF_kVc4A4M8N'
      project_number: 3
      ci_status: ${{ needs.get_pr_info.outputs.ci_status }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
